name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install minimal test deps
        run: |
          python -m pip install --upgrade pip
          pip install numpy matplotlib scipy
      - name: Lint (flake8)
        run: |
          pip install flake8
          flake8 honeybee_py || true
      - name: Run unit tests
        run: |
          python -m unittest discover -s honeybee_py/tests -p 'test_*.py'


